import { randomUUID } from 'node:crypto';
import { financeRepository } from '@/lib/backend/financeRepository.js';
import { deliveryRepository } from '@/lib/backend/deliveryRepository.js';

export const MERCHANT_MONTHLY_PRICE = Number(process.env.MERCHANT_MONTHLY_PRICE || 19.90);
export const RELAY_PICKUP_UNIT_PRICE = Number(process.env.RELAY_PICKUP_UNIT_PRICE || 1.50);
const now=()=>new Date().toISOString();
export async function createInvoice(input,actor){if(!input?.merchantId||!input?.merchant)throw new Error('MERCHANT_REQUIRED');if(!input?.period)throw new Error('PERIOD_REQUIRED');const t=now();return financeRepository.createInvoice({id:`FAC-${randomUUID()}`,merchantId:String(input.merchantId),merchant:String(input.merchant),period:String(input.period),amount:MERCHANT_MONTHLY_PRICE,status:'emise',date:t.slice(0,10),createdAt:t,createdBy:actor.sub,history:[{status:'emise',date:t,actorId:actor.sub}]});}
export async function createPayout(input,actor){if(!input?.relayPointId||!input?.relay)throw new Error('RELAY_REQUIRED');if(!input?.period)throw new Error('PERIOD_REQUIRED');const deliveries=await deliveryRepository.list({relayPointId:String(input.relayPointId),limit:10000});const parcels=deliveries.filter(d=>d.status==='Retiré').length;const t=now();return financeRepository.createPayout({id:`BON-${randomUUID()}`,relayPointId:String(input.relayPointId),relay:String(input.relay),period:String(input.period),parcels,unit:RELAY_PICKUP_UNIT_PRICE,amount:Number((parcels*RELAY_PICKUP_UNIT_PRICE).toFixed(2)),status:'emis',date:t.slice(0,10),createdAt:t,createdBy:actor.sub,history:[{status:'emis',date:t,actorId:actor.sub}]});}
export async function changeInvoiceStatus(id,status,actor){if(!['emise','payee','en_litige'].includes(status))throw new Error('INVALID_STATUS');const items=await financeRepository.listInvoices();const item=items.find(x=>String(x.id)===String(id));if(!item)throw new Error('NOT_FOUND');const t=now();return financeRepository.updateInvoice(id,{status,updatedAt:t,history:[...(item.history||[]),{status,date:t,actorId:actor.sub}]});}
export async function changePayoutStatus(id,status,actor){if(!['emis','paye'].includes(status))throw new Error('INVALID_STATUS');const items=await financeRepository.listPayouts();const item=items.find(x=>String(x.id)===String(id));if(!item)throw new Error('NOT_FOUND');const t=now();return financeRepository.updatePayout(id,{status,updatedAt:t,history:[...(item.history||[]),{status,date:t,actorId:actor.sub}]});}
