import {apiRequest,getAccessToken} from '@/services/api.js';
const STORAGE_KEY='relayflow_finance';const initial={invoices:[{id:1,merchantId:'demo-merchant-1',merchant:'Boulangerie Martin',period:'Juillet 2026',amount:19.90,status:'emise',date:'2026-07-20'}],payouts:[{id:1,relayPointId:'1',relay:'Relais République',period:'Juillet 2026',parcels:42,unit:1.50,amount:63,status:'emis'}],config:{merchantMonthlyPrice:19.90,relayPickupUnitPrice:1.50}};
function read(){if(typeof window==='undefined')return initial;try{const s=localStorage.getItem(STORAGE_KEY);if(!s){localStorage.setItem(STORAGE_KEY,JSON.stringify(initial));return initial;}return JSON.parse(s);}catch{return initial;}}function write(v){if(typeof window!=='undefined')localStorage.setItem(STORAGE_KEY,JSON.stringify(v));}
export const serviceFinance={
 async getAll(){if(getAccessToken()){const r=await apiRequest('/api/v1/finance/summary');return r.data;}return read();},
 async createInvoice(merchant,period,merchantId='demo-merchant-1'){if(getAccessToken()){const r=await apiRequest('/api/v1/finance/invoices',{method:'POST',body:JSON.stringify({merchant,merchantId,period})});return r.data;}const d=read(),id=Math.max(0,...d.invoices.map(i=>Number(i.id)||0))+1;d.invoices.unshift({id,merchantId,merchant,period,amount:d.config?.merchantMonthlyPrice||19.90,status:'emise',date:new Date().toISOString().slice(0,10)});write(d);return d.invoices[0];},
 async createPayout(relay,period,parcels,relayPointId='1'){if(getAccessToken()){const r=await apiRequest('/api/v1/finance/payouts',{method:'POST',body:JSON.stringify({relay,relayPointId,period})});return r.data;}const d=read(),id=Math.max(0,...d.payouts.map(i=>Number(i.id)||0))+1,count=Number(parcels)||0,unit=d.config?.relayPickupUnitPrice||1.50;d.payouts.unshift({id,relayPointId,relay,period,parcels:count,unit,amount:count*unit,status:'emis'});write(d);return d.payouts[0];},
 async updateInvoice(id,status){if(getAccessToken()){const r=await apiRequest(`/api/v1/finance/invoices/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});return r.data;}const d=read(),i=d.invoices.findIndex(x=>String(x.id)===String(id));if(i<0)return null;d.invoices[i]={...d.invoices[i],status};write(d);return d.invoices[i];},
 async updatePayout(id,status){if(getAccessToken()){const r=await apiRequest(`/api/v1/finance/payouts/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});return r.data;}const d=read(),i=d.payouts.findIndex(x=>String(x.id)===String(id));if(i<0)return null;d.payouts[i]={...d.payouts[i],status};write(d);return d.payouts[i];},
 async createInvoicesBulk(period,merchantIds=[]){if(getAccessToken()){const r=await apiRequest('/api/v1/finance/invoices/bulk',{method:'POST',body:JSON.stringify({period,merchantIds})});return r.data;}throw new Error('Connexion requise pour la génération groupée.');},
 async updateInvoicesBulk(invoiceIds,status='payee'){const r=await apiRequest('/api/v1/finance/invoices/bulk-status',{method:'PATCH',body:JSON.stringify({invoiceIds,status})});return r.data;},
 async createPayoutsBulk(period,relayPointIds=[]){const r=await apiRequest('/api/v1/finance/payouts/bulk',{method:'POST',body:JSON.stringify({period,relayPointIds})});return r.data;},
 async updatePayoutsBulk(payoutIds){const r=await apiRequest('/api/v1/finance/payouts/bulk-status',{method:'PATCH',body:JSON.stringify({payoutIds})});return r.data;},
};export default serviceFinance;
