"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {ArrowLeft, Printer} from "lucide-react";
import serviceLivraison from "@/services/ServiceLivraison.js";

function makeBars(text){let seed=0;for(const ch of text)seed=(seed*31+ch.charCodeAt(0))>>>0;return Array.from({length:56},(_,i)=>{seed=(1664525*seed+1013904223)>>>0;return 1+(seed%3)});}
export default function EtiquettePage(){const {id}=useParams();const [d,setD]=useState(null);useEffect(()=>{serviceLivraison.findById(id).then(setD)},[id]);const bars=useMemo(()=>makeBars(d?.reference||"LIVRAISON"),[d?.reference]);if(!d)return <main className="min-h-screen bg-white p-10 text-slate-900">Chargement...</main>;return <main className="min-h-screen bg-slate-100 p-4 text-slate-950 sm:p-8 print:bg-white print:p-0"><div className="mx-auto mb-4 flex max-w-3xl items-center justify-between print:hidden"><Link href={`/commercant/livraisons/${id}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft size={16}/> Retour</Link><button onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white"><Printer size={16}/> Imprimer l'étiquette</button></div><section className="mx-auto max-w-3xl border-2 border-slate-950 bg-white p-7 shadow-xl print:shadow-none"><div className="flex items-start justify-between gap-8 border-b-2 border-slate-950 pb-5"><div><p className="text-2xl font-black">Étiquette de livraison</p><p className="mt-1 text-xs font-bold uppercase tracking-[.18em] text-slate-500"></p></div><div className="text-right"><p className="text-xs font-bold uppercase text-slate-500">Référence</p><p className="mt-1 text-xl font-black">{d.reference}</p></div></div><div className="grid gap-8 py-7 sm:grid-cols-2"><Block title="Destinataire"><strong>{d.client?.firstName} {d.client?.lastName}</strong><span>{d.client?.phone||"Téléphone non renseigné"}</span></Block><Block title="Point relais"><strong>{d.relayPoint||d.relayName}</strong><span>Remise au comptoir</span></Block><Block title="Colis"><strong>{d.quantity||1} colis · {d.weight||0} kg</strong><span>{d.type||"Standard"}</span></Block><Block title="Transport"><strong>{d.carrierName||"Transporteur non renseigné"}</strong><span>Prévu le {d.date||"—"}</span></Block></div><div className="border-t-2 border-slate-950 pt-6"><div className="flex h-24 items-stretch justify-center gap-[2px] overflow-hidden bg-white px-4">{bars.map((w,i)=><span key={i} style={{width:`${w}px`}} className="block bg-black"/>)}</div><p className="mt-3 text-center font-mono text-lg font-bold tracking-[.22em]">{d.reference}</p><p className="mt-2 text-center text-[10px] text-slate-500">Code visuel de démonstration — utilisez la référence pour rechercher la livraison.</p></div>{d.contents&&<div className="mt-6 border-t border-slate-300 pt-4"><p className="text-xs font-bold uppercase text-slate-500">Contenu déclaré</p><p className="mt-1 text-sm font-semibold">{d.contents}</p></div>}</section></main>}
function Block({title,children}){return <div><p className="mb-2 text-[11px] font-black uppercase tracking-[.14em] text-slate-500">{title}</p><div className="flex flex-col gap-1 text-sm">{children}</div></div>}
