export const PARCEL_STATUS = {

    CREATED: "CREATED",

    IN_TRANSIT: "IN_TRANSIT",

    RECEIVED: "RECEIVED",

    AVAILABLE: "AVAILABLE",

    DELIVERED: "DELIVERED",

    INCIDENT: "INCIDENT",

    RETURN_PENDING: "RETURN_PENDING",

    RETURNED: "RETURNED"

};