"use client";
import Link from "next/link";
import {useState} from "react";
import {ArrowLeft, PackageSearch, Search, CheckCircle2, Circle} from "lucide-react";
import serviceLivraison from "@/services/ServiceLivraison.js";

const order=["Créée","En transit","Arrivé au point relais","Retiré"];
export default function PublicTrackingPage(){
 const [query,setQuery]=useState(""); const [delivery,setDelivery]=useState(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 async function submit(e){e.preventDefault();setLoading(true);setError(""); const all=await serviceLivraison.search(query); const exact=all.find(d=>String(d.reference).toLowerCase()===query.trim().toLowerCase()); setDelivery(exact||null); if(!exact)setError("Aucun colis trouvé avec cette référence."); setLoading(false)}
 const current=delivery?order.indexOf(delivery.status):-1;
 return <main className="min-h-screen bg-[#08111f] text-slate-100"><header className="border-b border-slate-800 bg-[#0b1422]"><div className="mx-auto flex h-20 max-w-5xl items-center justify-between px-5"><Link href="/" className="inline-flex rounded-full border border-blue-400/20 bg-blue-400/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[0.13em] text-blue-200"></Link><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-400 hover:text-white"><ArrowLeft size={16}/> Accueil</Link></div></header>
 <section className="mx-auto max-w-3xl px-5 py-16 sm:py-24"><div className="text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-500/10 text-blue-300"><PackageSearch size={25}/></span><p className="mt-5 text-xs font-black uppercase tracking-[.16em] text-blue-400">Suivi colis</p><h1 className="mt-3 text-4xl font-black tracking-tight">Où est votre colis ?</h1><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-slate-400">Saisissez le numéro de suivi communiqué par le commerçant. Aucun compte client n'est nécessaire.</p></div>
 <form onSubmit={submit} className="mx-auto mt-9 flex max-w-xl gap-2 rounded-2xl border border-slate-700 bg-[#111b2b] p-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex. LIV-00003" className="min-w-0 flex-1 bg-transparent px-3 py-3 text-sm text-white outline-none placeholder:text-slate-600"/><button disabled={!query.trim()||loading} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><Search size={16}/>{loading?"Recherche...":"Suivre"}</button></form>
 {error&&<p className="mx-auto mt-4 max-w-xl rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
 {delivery&&<div className="mt-8 rounded-3xl border border-slate-700 bg-[#111b2b] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Référence</p><p className="mt-1 text-xl font-black">{delivery.reference}</p></div><span className="rounded-full bg-blue-500/10 px-3 py-1.5 text-xs font-bold text-blue-300">{delivery.status}</span></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><Info label="Point relais" value={delivery.relayPoint||delivery.relayName}/><Info label="Client" value={`${delivery.client?.firstName||""} ${delivery.client?.lastName||""}`.trim()||"—"}/><Info label="Date prévue" value={delivery.date||"—"}/><Info label="Retrait avant" value={delivery.pickupDeadline?new Date(delivery.pickupDeadline).toLocaleDateString("fr-FR"):"À confirmer"}/></div>
 <div className="mt-8 border-t border-slate-800 pt-7"><p className="mb-5 text-sm font-black">Progression</p><div className="space-y-4">{order.map((status,i)=>{const done=current>=i || delivery.status==="Retiré"; const active=delivery.status===status; return <div key={status} className="flex items-center gap-3">{done?<CheckCircle2 size={20} className={active?"text-blue-300":"text-emerald-400"}/>:<Circle size={20} className="text-slate-700"/>}<span className={`text-sm font-bold ${done?"text-slate-200":"text-slate-600"}`}>{status}</span></div>})}</div>{["Refusé","Retour demandé","Retourné","Non récupéré"].includes(delivery.status)&&<p className="mt-5 rounded-xl border border-amber-500/20 bg-amber-500/10 p-3 text-sm text-amber-100">Statut particulier : {delivery.status}. Contactez le commerçant pour plus d'informations.</p>}</div></div>}
 </section></main>
}
function Info({label,value}){return <div className="rounded-2xl bg-slate-900/60 p-4"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-sm font-bold text-slate-200">{value}</p></div>}
