export const DEPARTEMENTS_FRANCE = [
  ['01','Ain'],['02','Aisne'],['03','Allier'],['04','Alpes-de-Haute-Provence'],['05','Hautes-Alpes'],['06','Alpes-Maritimes'],['07','Ardèche'],['08','Ardennes'],['09','Ariège'],['10','Aube'],['11','Aude'],['12','Aveyron'],['13','Bouches-du-Rhône'],['14','Calvados'],['15','Cantal'],['16','Charente'],['17','Charente-Maritime'],['18','Cher'],['19','Corrèze'],['2A','Corse-du-Sud'],['2B','Haute-Corse'],['21',"Côte-d'Or"],['22',"Côtes-d'Armor"],['23','Creuse'],['24','Dordogne'],['25','Doubs'],['26','Drôme'],['27','Eure'],['28','Eure-et-Loir'],['29','Finistère'],['30','Gard'],['31','Haute-Garonne'],['32','Gers'],['33','Gironde'],['34','Hérault'],['35','Ille-et-Vilaine'],['36','Indre'],['37','Indre-et-Loire'],['38','Isère'],['39','Jura'],['40','Landes'],['41','Loir-et-Cher'],['42','Loire'],['43','Haute-Loire'],['44','Loire-Atlantique'],['45','Loiret'],['46','Lot'],['47','Lot-et-Garonne'],['48','Lozère'],['49','Maine-et-Loire'],['50','Manche'],['51','Marne'],['52','Haute-Marne'],['53','Mayenne'],['54','Meurthe-et-Moselle'],['55','Meuse'],['56','Morbihan'],['57','Moselle'],['58','Nièvre'],['59','Nord'],['60','Oise'],['61','Orne'],['62','Pas-de-Calais'],['63','Puy-de-Dôme'],['64','Pyrénées-Atlantiques'],['65','Hautes-Pyrénées'],['66','Pyrénées-Orientales'],['67','Bas-Rhin'],['68','Haut-Rhin'],['69','Rhône'],['70','Haute-Saône'],['71','Saône-et-Loire'],['72','Sarthe'],['73','Savoie'],['74','Haute-Savoie'],['75','Paris'],['76','Seine-Maritime'],['77','Seine-et-Marne'],['78','Yvelines'],['79','Deux-Sèvres'],['80','Somme'],['81','Tarn'],['82','Tarn-et-Garonne'],['83','Var'],['84','Vaucluse'],['85','Vendée'],['86','Vienne'],['87','Haute-Vienne'],['88','Vosges'],['89','Yonne'],['90','Territoire de Belfort'],['91','Essonne'],['92','Hauts-de-Seine'],['93','Seine-Saint-Denis'],['94','Val-de-Marne'],['95',"Val-d'Oise"],['971','Guadeloupe'],['972','Martinique'],['973','Guyane'],['974','La Réunion'],['976','Mayotte'],
].map(([code, nom]) => ({ code, nom }));

// Villes principales proposées dans le formulaire. La saisie reste libre afin
// de ne pas bloquer les communes qui ne figurent pas dans cette liste.
export const VILLES_PRINCIPALES = [
  ['Bourg-en-Bresse','01'],['Laon','02'],['Moulins','03'],['Digne-les-Bains','04'],['Gap','05'],['Nice','06'],['Cannes','06'],['Antibes','06'],['Privas','07'],['Charleville-Mézières','08'],['Foix','09'],['Troyes','10'],['Carcassonne','11'],['Narbonne','11'],['Rodez','12'],['Marseille','13'],['Aix-en-Provence','13'],['Arles','13'],['Caen','14'],['Aurillac','15'],['Angoulême','16'],['La Rochelle','17'],['Bourges','18'],['Tulle','19'],['Ajaccio','2A'],['Bastia','2B'],['Dijon','21'],['Saint-Brieuc','22'],['Guéret','23'],['Périgueux','24'],['Besançon','25'],['Valence','26'],['Évreux','27'],['Chartres','28'],['Quimper','29'],['Brest','29'],['Nîmes','30'],['Alès','30'],['Toulouse','31'],['Auch','32'],['Bordeaux','33'],['Montpellier','34'],['Béziers','34'],['Sète','34'],['Rennes','35'],['Châteauroux','36'],['Tours','37'],['Grenoble','38'],['Lons-le-Saunier','39'],['Mont-de-Marsan','40'],['Blois','41'],['Saint-Étienne','42'],['Le Puy-en-Velay','43'],['Nantes','44'],['Saint-Nazaire','44'],['Orléans','45'],['Cahors','46'],['Agen','47'],['Mende','48'],['Angers','49'],['Saint-Lô','50'],['Reims','51'],['Châlons-en-Champagne','51'],['Chaumont','52'],['Laval','53'],['Nancy','54'],['Bar-le-Duc','55'],['Vannes','56'],['Lorient','56'],['Metz','57'],['Nevers','58'],['Lille','59'],['Roubaix','59'],['Tourcoing','59'],['Beauvais','60'],['Alençon','61'],['Arras','62'],['Clermont-Ferrand','63'],['Pau','64'],['Bayonne','64'],['Tarbes','65'],['Perpignan','66'],['Strasbourg','67'],['Colmar','68'],['Mulhouse','68'],['Lyon','69'],['Villefranche-sur-Saône','69'],['Vesoul','70'],['Mâcon','71'],['Le Mans','72'],['Chambéry','73'],['Annecy','74'],['Paris','75'],['Rouen','76'],['Le Havre','76'],['Melun','77'],['Versailles','78'],['Niort','79'],['Amiens','80'],['Albi','81'],['Montauban','82'],['Toulon','83'],['Draguignan','83'],['Avignon','84'],['La Roche-sur-Yon','85'],['Poitiers','86'],['Limoges','87'],['Épinal','88'],['Auxerre','89'],['Belfort','90'],['Évry-Courcouronnes','91'],['Nanterre','92'],['Bobigny','93'],['Créteil','94'],['Cergy','95'],['Basse-Terre','971'],['Pointe-à-Pitre','971'],['Fort-de-France','972'],['Cayenne','973'],['Saint-Denis','974'],['Mamoudzou','976'],
].map(([nom, departementCode]) => ({ nom, departementCode }));

export function departementParCode(code) {
  return DEPARTEMENTS_FRANCE.find((d) => d.code === code) || null;
}

export function departementPourVille(ville) {
  const normalized = String(ville || '').trim().toLocaleLowerCase('fr-FR');
  const match = VILLES_PRINCIPALES.find((v) => v.nom.toLocaleLowerCase('fr-FR') === normalized);
  return match ? departementParCode(match.departementCode) : null;
}
